#!/usr/bin/env php

<?php

define('BASE_PATH', __DIR__);

use App\Console\Commands\OneBillionRowsChallengeCommand;
use App\Console\Commands\OneBillionRowsChallengeForkCommand;

require_once __DIR__ . '/vendor/autoload.php';

$commands = [
    '1brc:execute' => OneBillionRowsChallengeCommand::class,
    '1brc:fork'    => OneBillionRowsChallengeForkCommand::class
];


$args = $_SERVER['argv'];

$command = $args[1] ?? null;

if ($command === null) {
    echo "No command provided.\n";
    exit(1);
}

$class = new $commands[$command]();
try {

    $startTime  = microtime(true);
    $statusCode = $class->execute(array_slice($args, 2));
    $endtime    = microtime(true);
    $duration   = $endtime - $startTime;
    echo "Execution time: " . number_format($duration, 2) . " seconds\n";
    exit($statusCode);
} catch (\Throwable $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}

